### ISSUE TITLE
Thermal Thruster can't be used until switching off it when bought

### ISSUE THREAD

**Issue by Blazephlozard** [Mikusch/tfgo#27]
Buying the Thermal Thruster immediately switches you to it, but you can't initiate a flight with it unless you switch off and back onto it.

**Comment by Mikusch** [comment]
Sorry for the delay, I have been quite busy the past few days.

This bug only happens if you buy the Thermal Thruster while holding a primary or melee weapon. Buying it with an active secondary weapon works just fine.

Since I couldn't figure out how to fix this, the gamemode will now longer attempt to switch to the Thermal Thruster. I will try to find a better solution for this in the future but I consider this "fixed" for now.
